import {
  SearchProfile,
  JobTrack,
  RoleType,
  Seniority,
  SkillCategory,
} from './types';

export const SEARCH_PROFILE: SearchProfile = {
  node: {
    track: JobTrack.NODE,
    priority: 'MAXIMUM',
    targetSeniorities: [
      Seniority.INTERNSHIP,
      Seniority.TRAINEE,
      Seniority.JUNIOR,
      Seniority.JUNIOR_MID,
      Seniority.UNSPECIFIED,
    ],
    nonPrimarySeniorities: [
      Seniority.MID,
      Seniority.MID_SENIOR,
      Seniority.SENIOR,
      Seniority.LEAD,
      Seniority.STAFF,
      Seniority.PRINCIPAL,
    ],
    technologies: {
      core: [
        'Node.js',
        'TypeScript',
        'NestJS',
        'REST API',
        'Backend',
        'PostgreSQL',
        'MySQL',
      ],
      strong: [
        'Express',
        'Fastify',
        'Docker',
        'Prisma',
        'ORM',
        'JWT',
        'SQL',
        'API Integration',
      ],
      complementary: [
        'MongoDB',
        'Redis',
        'Cache',
        'RabbitMQ',
        'AWS',
        'Microservices',
        'Queues',
        'Messaging',
        'CI/CD',
      ],
    },
  },
  php: {
    track: JobTrack.PHP,
    priority: 'HIGH',
    targetSeniorities: [
      Seniority.JUNIOR,
      Seniority.JUNIOR_MID,
      Seniority.MID,
      Seniority.UNSPECIFIED,
    ],
    excludedSeniorities: [
      Seniority.MID_SENIOR,
      Seniority.SENIOR,
      Seniority.LEAD,
      Seniority.STAFF,
      Seniority.PRINCIPAL,
    ],
    technologies: {
      core: [
        'PHP',
        'Laravel',
        'Symfony',
        'REST API',
        'MySQL',
        'PostgreSQL',
        'Backend',
      ],
      strong: ['Docker', 'JavaScript', 'Vue.js', 'SQL', 'API Integration'],
      legacy: ['PHP 5', 'CodeIgniter', 'Zend legado', 'jQuery'],
      excludedWhenCentral: ['WordPress', 'Magento', 'WooCommerce'],
    },
  },
  internship: {
    track: JobTrack.NODE_INTERNSHIP,
    requiresNodeJs: true,
    acceptedRoleTypes: [
      RoleType.BACKEND,
      RoleType.FULLSTACK,
      RoleType.SOFTWARE_ENGINEERING,
      RoleType.SOFTWARE_DEVELOPMENT,
    ],
  },
  fullstack: {
    acceptedBackendTracks: [JobTrack.NODE, JobTrack.PHP],
  },
  otherPrimaryStacks: ['Java', 'Spring', 'C#', '.NET', 'Go', 'Ruby', 'Python'],
  modalities: {
    accepted: ['REMOTE', 'HYBRID', 'ONSITE'],
    remote: {
      acceptedLocation: 'Brasil',
    },
    hybrid: {
      acceptedLocation: 'São Paulo e Grande São Paulo',
      locationRequiresManualReview: true,
    },
    onsite: {
      acceptedLocation: 'São Paulo e Grande São Paulo',
      locationRequiresManualReview: true,
    },
    baseLocation: 'São Paulo - SP',
  },
  acceptedEmploymentTypes: ['CLT', 'PJ', 'INTERNSHIP'],
  nonTargetEmploymentTypes: ['COOPERATIVE', 'TEMPORARY'],
  unknownEmploymentTypeIsAutomaticallyInvalid: false,
  salaryRequired: false,
  discoveryTitles: [
    'Backend Developer',
    'Back-end Developer',
    'Backend Engineer',
    'Software Engineer',
    'Software Developer',
    'Desenvolvedor Backend',
    'Desenvolvedor Back-end',
    'Desenvolvedor Node.js',
    'Node.js Developer',
    'Node Developer',
    'NestJS Developer',
    'PHP Developer',
    'Desenvolvedor PHP',
    'Full Stack Developer',
    'Fullstack Developer',
    'Desenvolvedor Full Stack',
    'Analista Desenvolvedor',
    'Analista de Sistemas',
    'Estágio em Desenvolvimento',
    'Estágio em Desenvolvimento de Software',
    'Estágio em Engenharia de Software',
    'Estágio Backend',
    'Estágio Back-end',
    'Estágio Fullstack',
    'Estágio Node.js',
  ],
  skillCategories: SkillCategory,
};
